### ISSUE TITLE
Add 2 tables to DB

### ISSUE THREAD

**Issue by andygrillo** [openeew/openeew-detection#18]
TABLE: `Devices`
`device_id` data type varchar
`intensity` data type decimal
`latitude` data type decimal
`longitude` data type decimal
`firmware_version` data type decimal
`device_type` data type decimal
`time_entered` data type decimal (we store as Unix time)

TABLE: `EEW_Output`
`event_id` data type varchar
`time_of_event` data type decimal (we store as Unix time)
`intensity` data type decimal
`latitude` data type decimal
`longitude` data type decimal
`sensor_ids` data type decimal
`time_entered` data type decimal (we store as Unix time)

**Comment by EgidioCaprino** [comment]
@andygrillo shall we implement some sort of version control for the database? What if the user updates the image and the database is changed? Maybe we can use [Liquibase](https://www.liquibase.org/)?
