### ISSUE TITLE
Add script that subscribes to device MQTT topic and writes to DB

### ISSUE THREAD

**Issue by andygrillo** [openeew/openeew-detection#22]
A script should subscribe to the MQTT broker (eg refer to [this](https://github.com/openeew/openeew-detection/blob/master/scripts/detection.py)), and write the incoming data to the `devices` [table](https://github.com/openeew/openeew-detection/blob/master/scripts/init_db.sql) in the database.

This will allow device latitude, longitudes, firmware version, etc to be stored in the table for reference later.

**Comment by EgidioCaprino** [comment]
`/device` topic sample:

```
{device_id: 2351n2x55, latitude: 19.35, longitude: -99.14, firmware_version: 1.2, device_type: esp32, time_entered: 1597685615}
```

**Comment by andygrillo** [comment]
corresponding issue for firmeware:
https://github.com/openeew/openeew-sensor/issues/7

**Comment by EgidioCaprino** [comment]
@andygrillo can we close this issue? It's been implemented in https://github.com/openeew/openeew-detection/pull/50

**Comment by andygrillo** [comment]
Yes!
