### ISSUE TITLE
The database writer script DBwriter.py does not exist

### ISSUE THREAD

**Issue by krook** [openeew/openeew-detection#40]
It seems we're missing the piece that writes to the PostgreSQL database.

**Comment by krook** [comment]
I believe the database writes are all captured now. Can you confirm @EgidioCaprino?

**Comment by EgidioCaprino** [comment]
Hi @krook 👋 Yes, you can use the [execute_statement](https://github.com/openeew/openeew-detection/blob/master/openeew/db.py) function. [Here](https://github.com/openeew/openeew-detection/blob/master/openeew/devices.py) you can find an example. Please let me know if any questions

**Comment by krook** [comment]
Yep, that's what I saw before. Thanks!
