### ISSUE TITLE
Add Grafana image to Docker

### ISSUE THREAD

**Issue by andygrillo** [openeew/openeew-detection#46]
This will allow visualization of sensor data, including real-time accelerations, sensor locations, and sensor status. Grafana can also be used to send alerts when sensors have been off, or other threshold events are met.

Grafana will need to be setup with the time-series database pre configured as a data source:
https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources

Image:
https://grafana.com/docs/grafana/latest/installation/docker/

**Comment by EgidioCaprino** [comment]
We now have a dedicated dashboard project
