### ISSUE TITLE
Add script that listens to /devices topic and stores values in devices table 

### ISSUE THREAD

**Issue by andygrillo** [openeew/openeew-detection#49]
Each device will publish its {device_id, latitude, longitude, firmware version, device_type, and time_entered} in JSON format to the MQTT broker.

We need a script which adds this sensor metadata to the `devices` table. You can see the structure of the database table [here](https://github.com/openeew/openeew-detection/blob/master/init_db.sql).

**Comment by EgidioCaprino** [comment]
@andygrillo can we close this issue? It should be implemented by https://github.com/openeew/openeew-detection/pull/50

**Comment by andygrillo** [comment]
Yes, agreed. Ill close now
