### ISSUE TITLE
Add GitHub Actions to the repository to automate lint checks

### ISSUE THREAD

**Issue by EdrianI** [openeew/openeew-detection#66]

**Comment by EgidioCaprino** [comment]
Hi @EdrianI what do you use for linting? Because `pylint` gives me a lot of errors. I can add the check to the Github action but we will need to fix all the errors before merging the branch. Could you help me with that?

**Comment by EdrianI** [comment]
@EgidioCaprino Pylint works but as you mentioned it does introduce technical debt. This usually happens when a linter is introduced after a project has already started. There are two linters I'm looking at; Pylint and Black. Black allows us to conform to the PEP8 formatting standards and pylint is a typical linter.

I'll add a PR with changes resulted from black this week. Afterwards, we can just check to make sure that any PR opened follows the PEP8 standard by running black's check. This is black : https://github.com/psf/black

It was my intention to make a GHA specifically for linters. So any push would run the lint, and any PR would require the lint checks to pass.

**Comment by EdrianI** [comment]
For now, we'll add black and I'll make a story for the work involved to pylint
